CREATE DATABASE readitusersDB;
USE readitusersDB;

CREATE TABLE users (
  id INT(11) AUTO_INCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL,
  googleId VARCHAR(255) NOT NULL,
  oauthId VARCHAR(255),
  PRIMARY KEY(id)
);

